Use donate and membership component from @debtcollective/union-component NPM package
debtcollective/home pull request #93
Opened 2021-03-02 22:28 UTC by orlando

**What:** Use donate and membership component from @debtcollective/union-component NPM package

**Why:** Closes https://app.asana.com/0/1168997577035609/1199546028191074

**How:**

- delete union component code
- import MembershipWidget and DonationWidget from [@debtcollective/union-component](https://www.npmjs.com/package/@debtcollective/union-component)

2021-03-02 23:12 UTC, arathjz approved these changes

2021-03-03 08:51 UTC, duranmla commented
Why we open a new PR we mentioned that the work to integrate has been done at https://github.com/debtcollective/home/pull/92 and the idea were for you to setup the `window` variables and merge that PR.

Can we ensure the other PR gets updated _(probably with some cherry pick from here)_ and merge the PR#92 instead of this?

2021-03-03 08:53 UTC, duranmla requested changes
Everything is cool, but I do not understand why we didn't support the previous PR.
_Can we include this changes there? The previous PR took this scope because of your comment https://github.com/debtcollective/home/pull/92#discussion_r583043707_

2021-03-08 21:55 UTC, orlando commented
Closing this in favor of https://github.com/debtcollective/home/pull/92

2021-03-08 21:55 UTC, closed without merging